### ISSUE TITLE
rxjs version incorrect?

### ISSUE THREAD

**Issue by KamelJabber** [CaptainCodeman/angular2-webpack-polyfill#1]
I had to change the rxjs to beta.2

That being said, I didn't actually clone the repo and tried to create it step by step manually, so I could have caused the issue.

The message I was getting was something about angular requires rxjs....beta.2

**Comment by CaptainCodeman** [comment]
Yes, that's just the warning because Angular 2 specifies an older version of rxjs. I switched to 4 and haven't had any issues with it (on a much larger project).

it can safely be ignored.
