### ISSUE TITLE
Polyfills needed if core.js not referenced separately

### ISSUE THREAD

**Issue by cah-chaitanya-munagala** [CaptainCodeman/angular2-webpack-polyfill#2]
If I don't want to reference core.js separately what all should I do? I commented out the script tag that downloads the core js from cdn and uncommented the section that says "polyfills needed if core.js not referenced separately:" in webpack.config.js.

But the app bombs when I try to run. I know I'm missing something but don't know what I am missing. Can you please provide some insight into this?

Thanks.

**Comment by CaptainCodeman** [comment]
Ah, sorry about that. There's also the reflect-metadata that is needed (so many shims and combinations!). The easiest way to get it is to add it to the list in the `webpack.config.js` file:

```
     'core-js/es6/array',
     'core-js/es6/map',
     'core-js/es6/string',
     'core-js/es6/symbol',
     'core-js/es7/reflect',
```

... and of course you need core.js added to `package.json` as well:

```
    "core-js": "^2.2.2",
```

The other option is to add the reflect-metadata package instead (but if you're using core, it's easier to use the one included).

**Comment by cah-chaitanya-munagala** [comment]
Thanks for the info. It works now. You are right...so many shims and combinations.

-Thanks

**Comment by CaptainCodeman** [comment]
:thumbsup:
