### ISSUE TITLE
webpackJsonp is not defined

### ISSUE THREAD

**Issue by davidoliveira** [CaptainCodeman/angular2-webpack-polyfill#3]
Hi,

I cloned the repo, npm run install and start, but when load it in bowser, I get the error:
app.js:1 Uncaught ReferenceError: webpackJsonp is not defined

I already made some search about this and try some things, but I can't found the solution. Do you know why this happens?

I have node 4.4.7 and npm 3.10.5 in my machine.

Thanks.

PS. Maybe you want to update your README and replace (run http://localhost:8080) by (run http://localhost:5000) to be equal with webpack.dev.js
![image](https://cloud.githubusercontent.com/assets/1504388/17133622/c63e718a-531e-11e6-81df-1a0e0b19b698.png)

**Comment by CaptainCodeman** [comment]
Sorry, I haven't seen that issue. It's possible there's been some newer update of a package that has affected things, I'll check it out.

Thanks for letting me know about the port - too much switching between different projects! :)

**Comment by CaptainCodeman** [comment]
It showed up when I updated webpack to the latest version. Setting the sort order of the injected scripts to 'auto' fixed it for me.

**Comment by davidoliveira** [comment]
Looking for your changes, I was close, but I missed the chunksSortMode property! You are the best!

Thank you! :+1:

**Comment by CaptainCodeman** [comment]
No problem, thanks for letting me know about it :thumbsup:
